services:
  picarx-dt:
    image: abarbie/picarx:latest
    environment:
      - ROS_HOSTNAME=picarx-dt
      - ROS_MASTER_URI=http://picarx-dt:11313
      - ROS_HOST_PORT=11313
    tty: true
    ports:
      - 11313:11313
    command: roscore -p 11313
    healthcheck:
      test: [ "CMD-SHELL", "curl $${ROS_MASTER_URI} || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 1s

  shadow-dt:
    image: abarbie/picarxpicarx:latest
    env_file:
      - ./core/dtp/env/picarx-dt.env
    tty: true
    command: /bin/bash -c "roslaunch arches_core digitalshadow_dt.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_left-pt:
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/dcmotor/
    image: abarbie/picarx/drivers/dcmotor:latest
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_left.launch i2c_port:=/dev/i2c-1"
    depends_on:
      picarx-dt:
        condition: service_healthy

  motor_right-pt:
    image: abarbie/picarx/drivers/dcmotor:latest
    tty: true
    env_file:
      - ./core/dtp/env/picarx.env
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/dcmotor:/root/catkin_ws/src/drivers/dcmotor
    command: /bin/bash -c "roslaunch picarx_dcmotor_driver dcmotor_right.launch i2c_port:=/dev/i2c-1"
    depends_on:
      picarx-dt:
        condition: service_healthy

  steering-pt:
    build:
      dockerfile: Dockerfile
      context: ./ros/drivers/clutchgear
    image: abarbie/picarx/emulators/clutchgear:latest
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/drivers/clutchgear:/root/catkin_ws/src/drivers/clutchgear
    command: /bin/bash -c "roslaunch picarx_clutchgear_driver ackermann_clutchgear_driver.launch i2c_port:=/dev/i2c-1"
    depends_on:
      picarx-dt:
        condition: service_healthy

  ackermann_skill-pt:
    build:
      dockerfile: Dockerfile
      context: ./ros/skills/ackermann_drive
    image: abarbie/picarx/skills/ackermann_drive:latest
    env_file:
      - ./core/dtp/env/picarx.env
    tty: true
    privileged: true
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/i2c-0:/dev/i2c-0
      - ./core:/root/catkin_ws/src/core
      - ./ros/skills/ackermann_drive:/root/catkin_ws/src/skills/ackermann_drive
    command: /bin/bash -c "roslaunch picarx_ackermann_drive ackermann_skill.launch"
    depends_on:
      picarx-dt:
        condition: service_healthy

networks:
  default:
    driver: bridge
