picarx:
 # Publish all joint states -----------------------------------
 joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

 # Position Controllers ---------------------------------------
 joint1_position_controller:
   type: velocity_controllers/JointVelocityController
   joint: joint_wheel_left
   pid: {p: 100.0, i: 0.01, d: 10.0}
 joint2_position_controller:
   type: velocity_controllers/JointVelocityController
   joint: joint_wheel_right
   pid: {p: 100.0, i: 0.01, d: 10.0}
 steering_servo_position_controller:
   type: position_controllers/JointPositionController
   joint: steer_servo_JOINT_steer_bar
   pid: {p: 100.0, i: 0.01, d: 10.0}